config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/home_admin', as: 'rails_admin'
  get 'transactions/new'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  root :to => "main#index"

  get "main/index" => "main#index"
  get "admin" => "admin/users#index"


  get 'conditions' => 'main#conditions'
  get 'terms' => 'main#terms'

  namespace :admin do
    resources :main
    resources :orders do
      collection do
        get :today
      end
    end
    resources :users
    resources :restaurants
  end

  resources :users do
    member do
      get :purchase

      # ajax btn
      get :paid
      get :completed
      get :cancelled
      get :big_bun

      # update order btn
      post :cancel_order
      post :not_yet_order
      post :yep_order

      get :review
      get :message

      get :liked
      get :kitchen
      get :food

      post :like
      post :unlike

      # conversation
      get :get_conversation_messages

    end
  end

  resources :chefs do
    resources :foods
    resources :big_buns
    resources :replies
    member do
      get :review
      get :approve

      # Menu
      get :add_dish
      post :save_dish
      get :add_big_bun
      get :menu

      # 5 btn
      get :sales
      get :summary
      get :advance
      get :delivering
      get :completed
      get :cancelled

      get :income
      get :rating
      get :message
      get :business

      #yep
      post :yep_or_not

      #report
      get :orders_to_csv

      # conversation
      get :get_conversation_messages

    end
  end

  resources :foods

  resources :restaurants do
    resources :orders, controller: :orders do
      member do
        post :transactions
      end
    end

    resources :comments do
      member do
        post :update_food_comment
      end

      collection do
        post :create_food_comment
      end
    end

    member do
      get :get_conversation_with_chef
    end
  end

  resources :big_buns do
    collection do
      post :user_get_big_bun
      post :user_send_big_bun_as_gift
    end
  end

  resources :conversations, only: [:create] do
    member do
      post :close
    end

    resources :messages, only: [:create]
  end



  # resources :orders do
  #   member do
  #     post :transactions
  #   end
  # end

  scope path: '/api/v1/', module: 'api_v1', as: 'v1'  do
    get '/search/keyword' => 'search#keyword'
    get '/search/filter' => 'search#filter'
    get '/cuisines/get_foods' => 'cuisines#get_foods'
    get '/cuisines/get_restaurants' => 'cuisines#get_restaurants'
  end
  scope path: '/api/v1/', module: 'api_v1', as: 'v1', defaults: { format: :json } do
    get '/getDishesByFilter' => 'mains#getDishesByFilter'
    get '/getRestaurantsByMap' => 'restaurants#getRestaurantsByMap'
    get '/check_delivery_location' => 'orders#check_delivery_location'
  end


end

app/models/chef.rb
class Chef < ApplicationRecord

	belongs_to :user

	has_one :restaurant

	has_many :food_comment_replies

	accepts_nested_attributes_for :restaurant,
		:allow_destroy => true,
	  :reject_if => :all_blank

	accepts_nested_attributes_for :user,
		:allow_destroy => true,
	  :reject_if => :all_blank
end

app/controllers/chefs_controller.rb
class ChefsController < ApplicationController

  before_action :find_chef_restaurant, :only =>[
    :show, :edit, :update, :review, :approve, :add_dish,
    :save_dish, :menu, :sales, :yep_or_not, :business, :summary,:advance,:delivering,
    :completed,:cancelled, :rating, :message,:orders_to_csv,:get_conversation_messages]


  before_action :find_user, :only =>[
    :show, :edit, :update, :review, :approve, :add_dish,
    :save_dish, :menu, :sales, :yep_or_not, :business, :summary,:advance,:delivering,
    :completed,:cancelled,:get_conversation_messages]

  # before_action :is_current_user?, :except => [:new]
  # before_action :has_authority?, :except => [:new]
  before_action :user_admin?, :only => [:approve, :review]
  before_action :find_orders, :only => [:sales,:summary, :delivering, :advance,:completed,:cancelled,:orders_to_csv]

  def new
    @user = User.new
    @chef = Chef.new
  end

  def create
    create_pass = true
    flash[:alert] = 'Chef create success!'

    @chef = Chef.new(chef_params)

    # check email
    if User.find_by(:email => user_params[:email])
      create_pass = false
      flash[:alert] << "user exist!"
    else
      # create user
      @user = User.new(user_params)
      @user.name = chef_params[:first_name]
      @user.foodie_id = chef_params[:first_name]
      @user.phone_number = chef_params[:phone_number]
      @user.is_chef = true

      if !params[:chef][:user_attributes][:password].blank?
        @user.password = params[:chef][:user_attributes][:password]
      else
        flash[:alert] << "password fail"
      end

      # save user pass
      if @user.save
        @chef.user = @user

        # save chef & restaurant & delivery & bulk_buys
        if @chef.save

          bulk_buy_time_to_utc

          if !bulk_buy_checked
            @chef.restaurant.bulk_buys.destroy_all
          end

          if !delivery_checked && @chef.restaurant.delivery
            @chef.restaurant.delivery.destroy_all
          end

        else
          @user.destroy
          create_pass = false
          flash[:alert] << "save chef fail"
        end

        # save user fail
      else
        create_pass = false
        flash[:alert] << "save user fail"
      end
    end

    if create_pass
      flash[:notice] = "Chef create done, please confirm by email."
      redirect_to main_index_path
    else

      @user = User.new
      @chef = Chef.new(chef_params)
      flash[:alert] << "Register chef fail"
      redirect_to new_chef_path
    end

  end

  def message
  end

  def get_conversation_messages
    conversation_id = params[:conversation]
    @conversation = @user.recieved_conversations.find(conversation_id)
    @recipient = User.find(@conversation.sender_id)
    @sender = User.find(@conversation.recipient_id)
    @messages = @conversation.messages

    respond_to do |format|
      format.js
    end
  end

  # show
  def sales
    @orders = @today_orders.where(["pick_up_time > ?", @datetime_now_to_utc])
    # @orders = Order.all.last(3)
  end

  def summary
    # Today's ORDERS
    @orders = @today_orders.where(["pick_up_time > ?",@datetime_now_to_utc])
    # @orders = Order.all.last(3)
    render_js
  end

  def advance
    not_today_orders = @paid_process_orders.where(order_status: "process").where.not(:pick_up_time => @today_time_range)
    advance_orders = not_today_orders.where(["pick_up_time > ?",@datetime_now_to_utc])
    @orders = advance_orders
    render_js
  end

  def delivering
    @orders = @paid_process_orders.where(order_status: "process").where(["pick_up_time < ?",@datetime_now_to_utc])
    render_js
  end

  def completed
    @orders = @paid_process_orders.where(:order_status => 'completed')
    render_js
  end

  def cancelled
    @orders = @paid_process_orders.where(:order_status => 'cancelled')
    render_js
  end

  def business
    @completed_orders = @chef.restaurant.orders.where(:order_status => 'completed')
    # 取得並顯示總收入
    @total_orders_income = @completed_orders.sum(:amount)
    # 取得並顯示總賣出份數
    @total_orders_count = @completed_orders.count()
    # 取得並顯示本月收入
    @this_month = Time.now.localtime.month
    @this_month_completed_orders = @completed_orders.where('extract(month from updated_at) = ?', @this_month)
    @this_month_income = @this_month_completed_orders.sum(:amount)
    # 取得並顯示評分數
    @food_avg_summary_score = @restaurant.food_avg_summary_score
    # 取得並顯示最受歡迎餐點
    @ships = OrderFoodShip.where(:order_id => @completed_orders.ids)
    @food_ids = @ships.pluck(:food_id)

    food_dict = {}
    @food_ids.each do |food_id|
      total_cnt = @ships.where(:food_id => food_id).sum(:quantity)
      food_dict[food_id] = total_cnt
    end

    if food_dict.size == 0
      @most_popular_quantity = 0
      @most_popular_food = nil
    else
      most_popular_food_id = food_dict.max_by{|k,v| v}[0]
      @most_popular_quantity = food_dict.max_by{|k,v| v}[1]
      @most_popular_food = Food.find(most_popular_food_id)
    end
  end

  def edit
  end

  def update
    if !params[:chef][:user_attributes][:password].blank?
      @chef.user.password = params[:chef][:user_attributes][:password]
      @chef.user.save!
    end

    if @chef.update!(chef_params)
      # 處理bulk_buy 時間 to utc
      bulk_buy_time_to_utc

      redirect_to sales_chef_path(@chef)
    else
      flash[:alert] = "update fail"
      render :action => :edit
    end
  end

  def review
  end

  def rating
    @star_type = params[:type]
    @all_food_comments = @chef.restaurant.food_comments
    @star_all_num = @all_food_comments.size
    @star_1_food_comments = @all_food_comments.where("summary_score >= ? AND summary_score < ?", 1,2)
    @star_1_num = @star_1_food_comments.size
    @star_2_food_comments = @all_food_comments.where("summary_score >= ? AND summary_score < ?", 2,3)
    @star_2_num = @star_2_food_comments.size
    @star_3_food_comments = @all_food_comments.where("summary_score >= ? AND summary_score < ?", 3,4)
    @star_3_num = @star_3_food_comments.size
    @star_4_food_comments = @all_food_comments.where("summary_score >= ? AND summary_score < ?", 4,4.5)
    @star_4_num = @star_4_food_comments.size
    @star_5_food_comments = @all_food_comments.where("summary_score >= ? AND summary_score <= ?", 4.5,5)
    @star_5_num = @star_5_food_comments.size

    # default rating 使用
    @food_comments = @all_food_comments

    if @star_type == "5"
      @food_comments = @star_5_food_comments
    elsif @star_type == "4"
      @food_comments = @star_4_food_comments
    elsif @star_type == "3"
      @food_comments = @star_3_food_comments
    elsif @star_type == "2"
      @food_comments = @star_2_food_comments
    elsif @star_type == "1"
      @food_comments = @star_1_food_comments
    elsif @star_type == "6"
      @food_comments = @all_food_comments
    end

    @load_more = params[:load_more]
    @food_comments = @food_comments.page(params[:page]).per(5)
    if @food_comments.last_page?
      @next_page = nil
    else
      @next_page = @food_comments.next_page
    end

    respond_to do |format|
      format.html
      format.js
    end
  end

  def approve
    @restaurant = @chef.restaurant
    if @restaurant.update(:is_approved => true)
      redirect_to sales_chef_path(@chef)
    else
      flash[:alert] = "approve fail"
      render :action => :review
    end
  end

  def menu
    @foods = @chef.restaurant.foods.all
    @big_buns = @chef.restaurant.big_buns.all
  end


  def yep_or_not
    submit = params[:commit]
    confirmation_number = params[:confirmation_number]
    order = Order.find(params[:order_id])

    if submit == "Yep!"
      if confirmation_number.present?
        if confirmation_number == order.confirmation_number
          order.order_status = "completed"
          order.save!
          flash[:notice] = "Successfully completed order"
        else
          flash[:alert] = "Confirmation number is wrong!"
        end
      else
        flash[:alert] = "Please input confirmation number"
      end

    else
      # 勾選原因, 評價完使用者後
      raise
      order.order_status = "cancelled"
      order.save!
      flash[:notice] = "Successfully cancel order"
    end
    redirect_to sales_chef_path(@chef)
  end

  def orders_to_csv
    report_pick_up_date_from = params[:report_pick_up_date_from] + "00:00:00"
    report_pick_up_date_to = params[:report_pick_up_date_to] + "00:00:00"

    orders = @restaurant.orders.where("created_at >= ? AND created_at <= ?", report_pick_up_date_from, report_pick_up_date_to)
    respond_to do |format|
      format.html
      format.csv { send_data orders.to_csv }
      format.xls # { send_data @products.to_csv(col_sep: "\t") }
    end
  end

  private

  def render_js
    respond_to do |format|
      format.js {render 'sales'}
    end
  end


  def chef_params
    params.require(:chef).permit(
      :first_name, :last_name, :phone_number, :birthday,
      :SSN, :routing_number, :account_number,

      :restaurant_attributes => [
        :id, :name, :address, :phone_number,:description,
        :city, :state, :ZIP, :tax_ID, :communication_method,
        :certificated_img, :certificated_num, :main_photo, :tax,
        :order_reach,

        :delivery_attributes => [
          :id, :min_order, :area, :distance, :completion_time,
        ],

        :bulk_buys_attributes => [
          :id, :cut_off_time, :location_1, :pick_up_time_1, :location_2, :pick_up_time_2
        ],

        :restaurant_cuisine_ships_attributes => [
          :id, :restaurant_id, :cuisine_id,
        ],

        :restaurant_dish_photos_attributes => [
          :id, :restaurant_id, :photo, :comment,
        ],
      ],

      :user_attributes => [
        :id, :email,

        :user_photo_attributes => [
          :id, :user_id, :photo,
        ],
      ],
    )
  end

  def user_params
    chef_params[:user_attributes]
  end

  def restaurant_params
    chef_params[:restaurant_attributes]
  end

  def delivery_params
    restaurant_params[:delivery_attributes]
  end

app/helpers/chefs_helper.rb
module ChefsHelper
	def setup_chef(chef)
	  chef.build_restaurant unless chef.restaurant
	  chef.build_user unless chef.user
	  chef.user.build_user_photo unless chef.user.user_photo
	  chef.restaurant.build_delivery unless chef.restaurant.delivery
	  if !chef.id
	  	2.times{chef.restaurant.bulk_buys.build}
		  3.times{chef.restaurant.restaurant_cuisine_ships.build}
		  3.times{chef.restaurant.restaurant_dish_photos.build}
		else
			bulk_buys_size = chef.restaurant.bulk_buys.size
			restaurant_cuisine_ships_size = chef.restaurant.restaurant_cuisine_ships.size
			restaurant_dish_photos_size = chef.restaurant.restaurant_dish_photos.size

			bulk_buys_request = 2-bulk_buys_size
			restaurant_cuisine_ships_request = 3-restaurant_cuisine_ships_size
			restaurant_dish_photos_request = 3-restaurant_dish_photos_size

			bulk_buys_request.times{chef.restaurant.bulk_buys.build}
		  restaurant_cuisine_ships_request.times{chef.restaurant.restaurant_cuisine_ships.build}
		  restaurant_dish_photos_request.times{chef.restaurant.restaurant_dish_photos.build}
	  end
	  chef
	end
end

app/views/chefs/_chef_banner.html.erb
<div class="four_btn mb25 mb0_sm">
  <a href="<%= sales_chef_path %>" class="my_btn_reserve border_none_radius">
    <i class="fa fa-shopping-cart" aria-hidden="true"></i>
    <p>My Sales</p>
  </a>
  <a href="<%= rating_chef_path %>" class="my_btn_reserve border_none_radius">
    <i class="fa fa-star" aria-hidden="true"></i>
    <p>My Rating</p>
  </a>
  <a href="<%= message_chef_path %>" class="my_btn_reserve border_none_radius">
    <i class="fa fa-comment" aria-hidden="true"></i>
    <p>My Message</p>
  </a>
  <a href="<%= business_chef_path %>" class="my_btn_reserve border_none_radius">
    <i class="business_icon_red" aria-hidden="true"></i>
    <i class="business_icon_white hidden" aria-hidden="true"></i>
    <p>Business Summary</p>
  </a>
</div>

<script type="text/javascript" charset="utf-8">
  $(document).ready(function(){
    var btn = $('a.my_btn_reserve[href*="' + location.pathname.split('/')[3] + '"]')
    btn.toggleClass('my_btn_reserve').toggleClass('my_btn');
    btn.find('[class^=business]').toggleClass('hidden')

  })
</script>

app/views/chefs/_food_rating.html.erb
<% @food_comments.each do |food_comment| %>
    <div class="black_border_block mt25_sm mrl5_sm mrl25_md" id="food_comment_<%= food_comment.id %>">
      <div class="row df_sm">
        <div class="col-md-2 col-sm-3 col-xs-5 col-xs-offset-1 col-sm-offset-0">
          <div class="square_img border_main_radius" style="background-image: url(<%= image_path 'tmp/kitchen_2.png' %>"></div>
        </div>
        <div class="col-md-2 col-sm-3 col-xs-5">
          <div class="square_img border_main_radius" style="background-image: url(<%= image_path 'tmp/kitchen_3.png' %>"></div>
        </div>
        <div class="col-md-6 col-sm-4 col-xs-12 vertical_space_around tac tal_sm">
          <h3 class="bold"><%= food_comment.food.name %></h3>
          <h4 class="bold mtbn_sm mtb20"><%= food_comment.user.name %></h4>
          <div class="show_rated_<%= rated_score(food_comment.summary_score) %> mt10 mtn_sm" style="font-size: 20px;"></div>
        </div>
        <div class="col-md-2 col-sm-2 hidden-xs">
          <!--如果有回覆紀錄Reply字串改成Edit-->
          <% if food_comment.food_comment_replies.size == 0%>
              <button class="my_btn comment_reply_btn flr">Reply</button>
          <% else %>
              <button class="my_btn comment_reply_btn flr">Edit</button>
          <% end %>
        </div>
      </div>
      <div class="row">
        <div class="col-md-10 col-md-offset-2 col-xs-12">
          <i class="gray_line"></i>
          <p><%= food_comment.comment%></p>
          <span class="pull-right gray"><%= food_comment.created_at.localtime.strftime("%Y/%m/%d")%></span>
        </div>
        <div class="col-md-10 col-md-offset-2 col-xs-12">
          <div class="comment_reply" style="<%= 'display:none;' unless food_comment.food_comment_replies.first %>">
            <i class="gray_line"></i>
            <h5 class="red bold">Reply</h5>
            <p style="word-break: break-all"><%= food_comment.food_comment_replies.first.content if food_comment.food_comment_replies.first %></p>
            <div class="clearfix"></div>
            <span class="pull-right gray"><%= food_comment.food_comment_replies.first.updated_at.localtime.strftime("%Y/%m/%d") if food_comment.food_comment_replies.first %></span>
          </div>
          <div class="comment_reply_textarea" style="display: none;">
            <i class="gray_line"></i>
            <!--如果有回覆了就直接噴在textarea上，textarea一開始不關有沒有回覆都要被render出來，就回覆也直接噴在上面但hidden-->
            <% if food_comment and food_comment.food_comment_replies.size > 0 %>
                <%= form_for food_comment.food_comment_replies.first, url: chef_reply_path(@chef,food_comment.food_comment_replies.first, :food_comment_id => food_comment), remote: true do |f| %>
                    <%= f.label :content, 'Reply', class:'bold red' %>
                    <%= f.text_area :content, style:'border-radius:5px;', rows:'5' %>
                    <%= f.submit :send, class:'flr my_btn', style:'width: 115px;height: 40px;' %>
                <% end %>
            <% else %>
                <%= form_for FoodCommentReply.new, url: chef_replies_path(@chef, :food_comment_id => food_comment), remote: true do |f| %>
                    <%= f.label :content, 'Reply', class:'bold red' %>
                    <%= f.text_area :content, style:'border-radius:5px;', rows:'5' %>
                    <%= f.submit :send, class:'flr my_btn', style:'width: 115px;height: 40px;' %>
                <% end %>
            <% end %>
          </div>
        </div>
      </div>
      <div class="col-md-2 col-sm-2 visible-xs tac">
        <!--如果有回覆紀錄Reply字串改成Edit-->
        <% if food_comment.food_comment_replies.size == 0%>
            <button class="my_btn comment_reply_btn mt20">Reply</button>
        <% else %>
            <button class="my_btn comment_reply_btn mt20">Edit</button>
        <% end %>
      </div>
    </div>
<% end %>

app/views/chefs/business.html.erb
<%= form_for setup_chef(@chef), :url => chef_path(@chef), :method => "patch" do |f| %>

    <%= render 'kitchen_photo',f:f ,pen_click:'pen_click' %>

    <div class="container">
      <section class="row">
        <div class="col-xs-12 basic_bg_top">
          <div class="row" name="kitchen_banner">
            <div class="col-xs-12 df_sm mb15 tac tal_sm">
              <%= render 'chef_photo' ,f:f ,pen_click:'pen_click' %>
              <h1 class="bold m0 ml20_sm ml40_md ml60_lg tal_sm"><%= @chef.restaurant.name%></h1>
            </div>
            <div class="col-xs-12">
              <%= render 'chef_banner' %>
            </div>
          </div>
        </div>
      </section>
    </div>
<% end %>

<div class="container">
  <section class="row">
    <div class="col-xs-12 basic_bg ui form">
      <div class="row">
        <div class="col-lg-6 col-lg-offset-3 col-md-8 col-md-offset-2 col-sm-10 col-sm-offset-1">
          <div class="row">
            <div class="col-xs-12 col-sm-8 col-sm-offset-2 p50">
              <div class="red_circular">
                <h2 class="bold red">USD $<%=@total_orders_income%></h2>
              </div>
            </div>
            <div class="col-xs-12">
              <h4 class="mtb20_sm mtb15 dib bold">Total orders:</h4>
              <h4 class="mtb20_sm mtb15 dib ml30"><%=@total_orders_count%></h4>
            </div>
            <div class="col-xs-12">
              <h4 class="mtb20_sm mtb15 dib bold">Total revenue:</h4>
              <h4 class="mtb20_sm mtb15 dib ml30">$<%=@total_orders_income%></h4>
            </div>
            <div class="col-xs-12">
              <h4 class="mtb20_sm mtb15 dib bold">Total sale this month: </h4>
              <h4 class="mtb20_sm mtb15 dib ml30">$<%= @this_month_income%></h4>
            </div>
            <div class="col-xs-12">
              <h4 class="mtb20_sm mtb15 dib bold">Rating:</h4>
              <h4 class="mtb20_sm mtb15 dib ml30"><%= @food_avg_summary_score%></h4>
            </div>
            <div class="col-xs-12">
              <h4 class="mtb20_sm mtb15 dib bold">Most popular item:</h4>
              <h4 class="mtb20_sm mtb15 dib_sm ml30_sm">
                <% if @most_popular_food.present?%>
                    <%= @most_popular_food.name %> / <%= @most_popular_quantity%>
                <%end%>
              </h4>
            </div>

            <%= form_for @chef, url: orders_to_csv_chef_path(@chef,format: "csv"), :method => :get do |f| %>
                <div class="col-xs-12">
                  <h4 class="mtb20_sm mtb15 dib bold">Sale detail report:</h4>
                </div>
                <div class="col-xs-2">
                  <h4 class="bold dib">From</h4>
                </div>
                <div class="col-xs-8">
                  <div class="field">
                    <%= date_field_tag :report_pick_up_date_from %>
                  </div>
                </div>
                <div class="col-xs-1">
                  <h2 class="mt0"><i class="fa fa-calendar mr10" aria-hidden="true"></i></h2>
                </div>
                <div class="clearfix mtb20_sm"></div>
                <div class="col-xs-2">
                  <h4 class="bold dib">To</h4>
                </div>
                <div class="col-xs-8">
                  <div class="field">
                    <%= date_field_tag :report_pick_up_date_to %>
                  </div>
                </div>
                <div class="col-xs-1">
                  <h2 class="mt0"><i class="fa fa-calendar mr10" aria-hidden="true"></i></h2>
                </div>
                <div class="col-xs-12 mtb20 tac">
                  <%= f.submit "Export", :class => "my_btn", :id => "export_report_btn"%>
                </div>

            <% end %>
          </div>
        </div>
      </div>
    </div>
  </section>
</div>

<script type="text/javascript">
  $( document ).ready(function() {
    $("#export_report_btn").removeAttr( "data-disable-with" )
  });
</script>

app/views/chefs/get_conversation_messages.js.erb
$('.message_modal').html("<%=j render 'common/message_room' %>");
$('.message_modal, .message_close').show();
$('.message_modal').show();
$('.message_body').scrollTop(1000000000);

app/views/chefs/review.html.erb
<div class="container chef-container center">
	<div class="row col-md-offset-1">
		<h3>
			<%=link_to "HOME", root_path%><span> > <%=params[:action]%></span>
		</h3>
	</div>
	<div class="row">
		<%= form_for setup_chef(@chef), :url => chef_path(@chef) do |f| %>

			<%= render :partial => 'form', :locals => { :f => f } %>

			<% if !@chef.restaurant.is_approved%>
				<div class="row form_control col-md-12" id="chef-approve-btn">
					<%= link_to "APPROVE", approve_chef_path(@chef), :class=>"btn btn-success btn-lg"%>
				</div>
			<%end%>

		<% end %>
	</div>
</div>


<script>

</script>

app/views/chefs/show.html.erb
<div class="container chef-container center" >
  <div class="row col-md-offset-1">
    <h3>
      <%=link_to "HOME", root_path%><span> > <%=params[:action]%></span>
    </h3>
  </div>
  <div class="row">
    <div class="row container chef-sub-container center">
      <div class="col-md-12" id="chef-show-bg-img" style="background-image: url(<%=asset_path(@chef.restaurant.main_photo.url)%>)">

        <div class="col-md-4">
          <% if @chef.user.user_photo && @chef.user.user_photo.photo.exists? %>
              <%= image_tag(@chef.user.user_photo.photo(:thumb))%>
          <%end%>
        </div>
        <div class="col-md-4" id="restaurant_name"><%= @chef.restaurant.name%></div>
        <% if current_user == @user%>
            <div class="btn btn-default col-md-2 right" id="chef-edit-btn">
              <i class="fa fa-pencil" aria-hidden="true"> <%= link_to "Edit Profile", edit_chef_path(@chef) %></i>
            </div>
        <%end%>
        <% if current_user.is_admin %>
            <div class="btn btn-success col-md-2 right" id="chef-review-btn">
              <i class="fa fa-eye" aria-hidden="true"> <%= link_to "Review Chef", review_chef_path(@chef) %></i>
            </div>
        <%end%>
      </div>
      <div class="col-md-12">
        <h3>About</h3>
        <p>
          <%= @chef.restaurant.description%>
        </p>
      </div>

      <div class="clearfix"></div>

      <div class="row">
        <div class="col-md-12">
          <%= link_to 'add dish',new_chef_food_path(@chef.id),:class=>"btn btn-primary"%>
          <%= link_to 'add bigbun', new_chef_big_bun_path(@chef.id),:class=>"btn btn-warning"%>
          <%= link_to 'set Menu',menu_chef_path(@chef.id),:class=>"btn btn-default"%>
        </div>
      </div>

      <div class="clearfix"></div>

      <div class="row" id="chef-menu-set-row">

        <!-- Sales -->
        <%= link_to sales_chef_path(@chef.id), :remote => true do%>
            <div class="col-md-offset-1 col-md-2 chef-menu-set" id='chef-sales'>
              <div class="col-md-12">
                <i class="fa fa-file-text" aria-hidden="true"></i>
              </div>
              <div class="col-md-12">
                Sales
              </div>
            </div>
        <%end%>

        <div class="col-md-2 chef-menu-set" id='chef-income'>
          <div class="col-md-12">
            <i class="fa fa-money" aria-hidden="true"></i>
          </div>
          <div class="col-md-12">
            Income
          </div>
        </div>

        <div class="col-md-2 chef-menu-set" id='chef-rating'>
          <div class="col-md-12">
            <i class="fa fa-star-o" aria-hidden="true"></i>
          </div>
          <div class="col-md-12">
            Rating
          </div>
        </div>

        <div class="col-md-2 chef-menu-set" id='chef-message'>
          <div class="col-md-12">
            <i class="fa fa-weixin" aria-hidden="true"></i>
          </div>
          <div class="col-md-12">
            Message
          </div>
        </div>

        <div class="col-md-2 chef-menu-set" id='chef-business'>
          <div class="col-md-12">
            <i class="fa fa-clock-o" aria-hidden="true"></i>
          </div>
          <div class="col-md-12">
            Business
          </div>
        </div>

      </div>
    </div>
  </div>

  <div class="row">
    <div class="row container chef-sub-container center" id="event_area">
    </div>
  </div>
</div>