config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/home_admin', as: 'rails_admin'
  get 'transactions/new'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  root :to => "main#index"

  get "main/index" => "main#index"
  get "admin" => "admin/users#index"


  get 'conditions' => 'main#conditions'
  get 'terms' => 'main#terms'

  namespace :admin do
    resources :main
    resources :orders do
      collection do
        get :today
      end
    end
    resources :users
    resources :restaurants
  end

  resources :users do
    member do
      get :purchase

      # ajax btn
      get :paid
      get :completed
      get :cancelled
      get :big_bun

      # update order btn
      post :cancel_order
      post :not_yet_order
      post :yep_order

      get :review
      get :message

      get :liked
      get :kitchen
      get :food

      post :like
      post :unlike

      # conversation
      get :get_conversation_messages

    end
  end

  resources :chefs do
    resources :foods
    resources :big_buns
    resources :replies
    member do
      get :review
      get :approve

      # Menu
      get :add_dish
      post :save_dish
      get :add_big_bun
      get :menu

      # 5 btn
      get :sales
      get :summary
      get :advance
      get :delivering
      get :completed
      get :cancelled

      get :income
      get :rating
      get :message
      get :business

      #yep
      post :yep_or_not

      #report
      get :orders_to_csv

      # conversation
      get :get_conversation_messages

    end
  end

  resources :foods

  resources :restaurants do
    resources :orders, controller: :orders do
      member do
        post :transactions
      end
    end

    resources :comments do
      member do
        post :update_food_comment
      end

      collection do
        post :create_food_comment
      end
    end

    member do
      get :get_conversation_with_chef
    end
  end

  resources :big_buns do
    collection do
      post :user_get_big_bun
      post :user_send_big_bun_as_gift
    end
  end

  resources :conversations, only: [:create] do
    member do
      post :close
    end

    resources :messages, only: [:create]
  end



  # resources :orders do
  #   member do
  #     post :transactions
  #   end
  # end

  scope path: '/api/v1/', module: 'api_v1', as: 'v1'  do
    get '/search/keyword' => 'search#keyword'
    get '/search/filter' => 'search#filter'
    get '/cuisines/get_foods' => 'cuisines#get_foods'
    get '/cuisines/get_restaurants' => 'cuisines#get_restaurants'
  end
  scope path: '/api/v1/', module: 'api_v1', as: 'v1', defaults: { format: :json } do
    get '/getDishesByFilter' => 'mains#getDishesByFilter'
    get '/getRestaurantsByMap' => 'restaurants#getRestaurantsByMap'
    get '/check_delivery_location' => 'orders#check_delivery_location'
  end


end

app/models/order.rb
class Order < ApplicationRecord

  belongs_to :restaurant
  belongs_to :user
  belongs_to :bulk_buy

  has_many :order_food_ships
  has_many :foods, :through => :order_food_ships

  has_many :user_big_bun_ships
  has_many :big_buns, :through => :user_big_bun_ships

  accepts_nested_attributes_for :order_food_ships,
                                allow_destroy: true,
                                reject_if: :all_blank
  after_create :update_order_price

  def year_filter
  end

  def month_filter
  end

  def week_filter
  end

  def update_order_price
    update(amount: calc_amount)
    update(subtotal: calc_subtotal)
    update(tax: calc_tax)
  end

  def calc_amount
    calc_subtotal + calc_tax
  end

  def calc_subtotal
    order_food_ships.pluck(:amount).reduce(:+).to_f
  end

  def calc_tax
    (calc_subtotal * ( StateTaxRateShip.find_by(state_ref: restaurant.state).tax_rate)).round(3)
  end

  # def calc_delivery
  # 	restaurant.delivery.cost || 0
  # end

  def self.to_csv(options = {})
    CSV.generate(options) do |csv|
      csv << column_names
      all.each do |order|
        csv << order.attributes.values_at(*column_names)
      end
    end
  end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController

	layout "admin"
	# before_action :authenticate_user!
  before_action :user_admin?

	def index
		if params[:restaurant]
			@restaurant_search= Restaurant.new(:name => params[:restaurant][:name])
			restaurant_ids = Restaurant.where('name LIKE ?', "%#{params[:restaurant][:name]}%").pluck(:id)
			@q = Order.where(:restaurant_id => restaurant_ids).ransack(params[:q])

		elsif params[:user]
			@user_search = User.new(:foodie_id => params[:user][:foodie_id])
			user_ids = User.where('foodie_id LIKE ?', "%#{params[:user][:foodie_id]}%").pluck(:id)
			@q = Order.where(:user_id => user_ids).ransack(params[:q])

		else
			@restaurant_search = Restaurant.new
			@user_search = User.new
			@q = Order.ransack(params[:q])
		end

    @orders = @q.result(distinct: true)
    @orders = @orders.page(params[:page]).per(5)
	end

	def today
		@orders = Order.where("created_at >= ?", Time.zone.now.beginning_of_day)

		if params[:restaurant]
			@restaurant_search= Restaurant.new(:name => params[:restaurant][:name])
			restaurant_ids = Restaurant.where('name LIKE ?', "%#{params[:restaurant][:name]}%").pluck(:id)
			@q = @orders.where(:restaurant_id => restaurant_ids).ransack(params[:q])

		elsif params[:user]
			@user_search = User.new(:foodie_id => params[:user][:foodie_id])
			user_ids = User.where('foodie_id LIKE ?', "%#{params[:user][:foodie_id]}%").pluck(:id)
			@q = @orders.where(:user_id => user_ids).ransack(params[:q])

		else
			@restaurant_search = Restaurant.new
			@user_search = User.new
			@q = @orders.ransack(params[:q])
		end

    @orders = @q.result(distinct: true)
    @orders = @orders.page(params[:page]).per(5)
	end

end

app/controllers/api_v1/orders_controller.rb
class ApiV1::OrdersController < ApplicationController

  def check_delivery_location
    @restaurant = Restaurant.find(params[:restaurant_id])
    lat, long = Geocoder.coordinates(params[:text])
    distance = @restaurant.distance_to([lat, long], :km)
    if @restaurant.delivery && distance < @restaurant.delivery.distance
      render json: { status: 'success', message: 'Your location is good to delivery!' }
    elsif @restaurant.delivery && distance > @restaurant.delivery.distance
      render json: { status: 'error', message: "Your location too far away, we couldn't offer service sorry #{distance}km!" }
    else
      render json: { status: 'error', message: 'Please enter right address or valid address!' }
    end
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  skip_before_filter :verify_authenticity_token
  before_action :find_order, :except => [:new,:create]
  before_action :find_restaurant
  before_action :is_chef?

  Braintree::Configuration.environment = :sandbox
  Braintree::Configuration.merchant_id = "72yk9y5dxms9gxf9"
  Braintree::Configuration.public_key = "n3tn23y52b346z3x"
  Braintree::Configuration.private_key = "dd8841579f3ee81053baddadbb4da98a"

  def new
    @order = Order.new
    @restaurant = Restaurant.find(params[:restaurant_id])

    state = @restaurant.state
    @tax_rate = StateTaxRateShip.find_by(:state_ref => state).tax_rate

    order_date = params[:date].to_date
    date_now = Time.now.localtime.to_date

    if order_date == date_now
      # check cut off time
      # time_now = Time.now.localtime
      time_now = Time.now.at_beginning_of_day
      @pick_up_time_array = []
      @time_location_dictionary = []

      @restaurant.bulk_buys.each do |bulk_buy|

        if bulk_buy.pick_up_time_1.present?
          pick_up_time = bulk_buy.pick_up_time_1.localtime.strftime("%H:%M:%S").to_time

          if pick_up_time > time_now

            if pick_up_time > time_now
              @pick_up_time_array << bulk_buy.pick_up_time_1.localtime.strftime("%H:%M:%S")
              dict = {}
              dict[:pick_up_time] = bulk_buy.pick_up_time_1.localtime.strftime("%H:%M:%S")
              dict[:location] = bulk_buy.location_1
              dict[:bulk_buy_id] = bulk_buy.id
              @time_location_dictionary << dict
            end
          end
        end

        if bulk_buy.pick_up_time_2.present?
          pick_up_time = bulk_buy.pick_up_time_2.localtime.strftime("%H:%M:%S").to_time

          if pick_up_time > time_now
            @pick_up_time_array << bulk_buy.pick_up_time_2.localtime.strftime("%H:%M:%S")
            dict = {}
            dict[:pick_up_time] = bulk_buy.pick_up_time_2.localtime.strftime("%H:%M:%S")
            dict[:location] = bulk_buy.location_1
            dict[:bulk_buy_id] = bulk_buy.id
            @time_location_dictionary << dict
          end
        end
      end

    else
      # give all pick_up_time
      bulk_buys = @restaurant.bulk_buys
      @pick_up_time_array = []
      @time_location_dictionary = []

      bulk_buys.each do |bulk_buy|

        # time_1
        if bulk_buy.pick_up_time_1
          @pick_up_time_array << bulk_buy.pick_up_time_1.localtime.strftime("%H:%M:%S")
          dict = {}
          dict[:pick_up_time] = bulk_buy.pick_up_time_1.localtime.strftime("%H:%M:%S")
          dict[:location] = bulk_buy.location_1
          dict[:bulk_buy_id] = bulk_buy.id
          @time_location_dictionary << dict
        end

        # time_2
        if bulk_buy.pick_up_time_2
          @pick_up_time_array << bulk_buy.pick_up_time_2.localtime.strftime("%H:%M:%S")
          dict = {}
          dict[:pick_up_time] = bulk_buy.pick_up_time_2.localtime.strftime("%H:%M:%S")
          dict[:location] = bulk_buy.location_2
          dict[:bulk_buy_id] = bulk_buy.id
          @time_location_dictionary << dict
        end
      end
    end

  end

  def create
    @order = current_user.orders.new(orders_params)
    @order.pick_up_time = get_pick_up_time
    @order.customer_name = current_user.name
    @order.payment_status = 'unpaid'
    @order.order_status = 'process'

    @error = false
    # check delivery order_min
    if orders_params[:shipping_method] == "delivery"
      check_delivery_min_order(params[:food])
    end

    if !@error && @order.save
      create_user_bigbun(params[:order][:'bigbun-id'])
      cookies.delete(:cart_list, path: '/')

      flash[:alert] = "Successfully create order!"
      redirect_to restaurant_order_path(@restaurant,@order)
    else
      flash[:alert] << "Fail new order!"
      render 'new'
    end

  end

  def show
    @client_token = Braintree::ClientToken.generate

    case @order.payment_status
    when 'unpaid' ;@thankyou = false
    when 'paid' ;@thankyou = true
    end

  end

  def transactions

    nonce_from_the_client = params["payment-method-nonce"]
    result = Braintree::Transaction.sale(
      :amount => @order.amount,
      :payment_method_nonce => nonce_from_the_client,
      :options => {
        :submit_for_settlement => true
      }
    )

    if result.success?
      @order.update(orders_params)
      @order.payment_status = "paid"
      @order.confirmation_number = result.transaction.id
      @order.save!

      flash[:notice] = "Successfully paid!"
      @thankyou = true
      redirect_to restaurant_order_path(@restaurant.id,@order.id)
    else
      render :show
    end

  end

  private

  def get_restaurant_from_cookies
    if cookies[:cart_list]
      cart = JSON.parse(cookies[:cart_list])
      keys = cart.keys.select do |key|
        cart[key].keys.select { |x| x.match(/food_\d/) }
      end
      id = keys.last.gsub('restaurant_','')
      Restaurant.find(id)
    end
  end

  def find_order
    @order = Order.find(params[:id])
  end

  def find_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def orders_params
    params.require(:order).permit(:shipping_method, :shipping_place,:restaurant_id, :bulk_buy_id,
                                  :mobile_number, :email, :billing_address, :pick_up_time,
                                  :billing_city, :billing_state, :billing_zip_code,

                                  order_food_ships_attributes: [
                                    :food_id, :quantity
                                  ])
  end

  def get_pick_up_time
    # Save to utc
    (params[:date] + ' ' + params[:order][:pick_up_time]).to_time.utc
  end

  def create_user_bigbun(params)
    if params
      # params.each do |key|
      current_user.user_big_bun_ships.find_or_create_by(order_id: @order.id, big_bun_id: params.to_i)
      # end
    end
  end

  def is_chef?
    if current_user && current_user.is_chef
      flash[:alert] = "Chef can't build order!"
      redirect_to root_path
    else
      return true
    end
  end

  def check_delivery_min_order(foods_hash)
    restaurant = Restaurant.find(orders_params[:restaurant_id])
    min_order = restaurant.delivery.min_order

    total_amount = 0

    foods_hash.each do |key,value|
      food_price = Food.find(key).price
      quantity = value.to_f
      amount = food_price*quantity
      total_amount += amount
    end

    raise

    if total_amount < min_order
      @error = true
      flash[:alert] << "your oreder amount is under delivery min_order"
    end
  end

end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/api_v1/orders_helper.rb
module ApiV1::OrdersHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
  def us_states
    [
      ['Alabama', 'AL'],
      ['Alaska', 'AK'],
      ['Arizona', 'AZ'],
      ['Arkansas', 'AR'],
      ['California', 'CA'],
      ['Colorado', 'CO'],
      ['Connecticut', 'CT'],
      ['Delaware', 'DE'],
      ['District of Columbia', 'DC'],
      ['Florida', 'FL'],
      ['Georgia', 'GA'],
      ['Hawaii', 'HI'],
      ['Idaho', 'ID'],
      ['Illinois', 'IL'],
      ['Indiana', 'IN'],
      ['Iowa', 'IA'],
      ['Kansas', 'KS'],
      ['Kentucky', 'KY'],
      ['Louisiana', 'LA'],
      ['Maine', 'ME'],
      ['Maryland', 'MD'],
      ['Massachusetts', 'MA'],
      ['Michigan', 'MI'],
      ['Minnesota', 'MN'],
      ['Mississippi', 'MS'],
      ['Missouri', 'MO'],
      ['Montana', 'MT'],
      ['Nebraska', 'NE'],
      ['Nevada', 'NV'],
      ['New Hampshire', 'NH'],
      ['New Jersey', 'NJ'],
      ['New Mexico', 'NM'],
      ['New York', 'NY'],
      ['North Carolina', 'NC'],
      ['North Dakota', 'ND'],
      ['Ohio', 'OH'],
      ['Oklahoma', 'OK'],
      ['Oregon', 'OR'],
      ['Pennsylvania', 'PA'],
      ['Puerto Rico', 'PR'],
      ['Rhode Island', 'RI'],
      ['South Carolina', 'SC'],
      ['South Dakota', 'SD'],
      ['Tennessee', 'TN'],
      ['Texas', 'TX'],
      ['Utah', 'UT'],
      ['Vermont', 'VT'],
      ['Virginia', 'VA'],
      ['Washington', 'WA'],
      ['West Virginia', 'WV'],
      ['Wisconsin', 'WI'],
      ['Wyoming', 'WY']
    ]
  end

  def deal_params_date
    params[:date].to_time.strftime('%F')
  rescue
    Date.current.to_time.strftime('%F')
  end

  def deal_delivery_time(bulk_buy_times)
    if bulk_buy_times.present?
    else
      Time.now
    end
  end
end

app/views/admin/orders/index.html.erb
<div id="page-content-wrapper">
  <div class="container-fluid">
    <div class="row">
      <h3><%=link_to "System Admin", admin_main_index_path %> | All Orders </h3>
    </div>
    <div class="row">
      <div class="col-md-12">
        <div id="custom-search-input">
          <div class="input-group col-md-12">
            <%= form_for @restaurant_search, url: admin_main_index_path, :method => :get do |f| %>
              <%= f.label :name,"Restaurant Name" %>
              <%= f.search_field :name %>

              <%= f.submit "Search", :class => "order-filter-btn"%>
            <% end %>
          </div>
          <div class="input-group col-md-12">
            <%= form_for @user_search, url: admin_main_index_path, :method => :get do |f| %>
              <%= f.label :foodie_id,"foodie_id"  %>
              <%= f.search_field :foodie_id %>

              <%= f.submit "Search"%>
            <% end %>
          </div>
        </div>
      </div>
      <div class="col-md-12">
        <table class="table table-striped table-hover">
          <thead>
            <tr>
              <th>Order ID</th>
              <th>Restaurant Name</th>
              <th>User foodie_id</th>
              <th>Total Acount</th>
              <th><%= sort_link(@q, :created_at, 'created at') %></th>
              <th>status</th>
            </tr>
          </thead>
          <tbody>
            <% @orders.each do |order|%>
              <tr>
                <td><%= order.id%></td>
                <td><%= order.restaurant.name%></td>
                <td><%= order.user.foodie_id%></td>
                <td><%= order.amount%></td>
                <td><%= order.created_at%></td>
                <td><%= order.order_status%></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>

  <div class="center" style="text-align: center; font-size: 20px;">
    <%= paginate @orders %>
  </div>
</div>

app/views/admin/orders/today.html.erb
<div id="page-content-wrapper">
  <div class="container-fluid">
    <div class="row">
      <h3><%=link_to "System Admin", admin_main_index_path %> | Today's Orders</h3>
    </div>
    <div class="row">
      <div class="col-md-12">
        <div id="custom-search-input">
          <div class="input-group col-md-12">
            <%= form_for @restaurant_search, url: admin_main_index_path, :method => :get do |f| %>
              <%= f.label :name,"Restaurant Name" %>
              <%= f.search_field :name %>

              <%= f.submit "Search", :class => "order-filter-btn"%>
            <% end %>
          </div>
          <div class="input-group col-md-12">
            <%= form_for @user_search, url: admin_main_index_path, :method => :get do |f| %>
              <%= f.label :foodie_id,"foodie_id"  %>
              <%= f.search_field :foodie_id %>

              <%= f.submit "Search"%>
            <% end %>
          </div>
        </div>
      </div>
      <div class="col-md-12">
        <table class="table table-striped table-hover">
          <thead>
            <tr>
              <th>Order ID</th>
              <th>Restaurant Name</th>
              <th>User foodie_id</th>
              <th>Total Acount</th>
              <th><%= sort_link(@q, :created_at, 'created at') %></th>
              <th>status</th>
            </tr>
          </thead>
          <tbody>
            <% @orders.each do |order|%>
              <tr>
                <td><%= order.id%></td>
                <td><%= order.restaurant.name%></td>
                <td><%= order.user.foodie_id%></td>
                <td><%= order.amount%></td>
                <td><%= order.created_at%></td>
                <td><%= order.order_status%></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>

  <div class="center" style="text-align: center; font-size: 20px;">
    <%= paginate @orders %>
  </div>
</div>