config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/home_admin', as: 'rails_admin'
  get 'transactions/new'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  root :to => "main#index"

  get "main/index" => "main#index"
  get "admin" => "admin/users#index"


  get 'conditions' => 'main#conditions'
  get 'terms' => 'main#terms'

  namespace :admin do
    resources :main
    resources :orders do
      collection do
        get :today
      end
    end
    resources :users
    resources :restaurants
  end

  resources :users do
    member do
      get :purchase

      # ajax btn
      get :paid
      get :completed
      get :cancelled
      get :big_bun

      # update order btn
      post :cancel_order
      post :not_yet_order
      post :yep_order

      get :review
      get :message

      get :liked
      get :kitchen
      get :food

      post :like
      post :unlike

      # conversation
      get :get_conversation_messages

    end
  end

  resources :chefs do
    resources :foods
    resources :big_buns
    resources :replies
    member do
      get :review
      get :approve

      # Menu
      get :add_dish
      post :save_dish
      get :add_big_bun
      get :menu

      # 5 btn
      get :sales
      get :summary
      get :advance
      get :delivering
      get :completed
      get :cancelled

      get :income
      get :rating
      get :message
      get :business

      #yep
      post :yep_or_not

      #report
      get :orders_to_csv

      # conversation
      get :get_conversation_messages

    end
  end

  resources :foods

  resources :restaurants do
    resources :orders, controller: :orders do
      member do
        post :transactions
      end
    end

    resources :comments do
      member do
        post :update_food_comment
      end

      collection do
        post :create_food_comment
      end
    end

    member do
      get :get_conversation_with_chef
    end
  end

  resources :big_buns do
    collection do
      post :user_get_big_bun
      post :user_send_big_bun_as_gift
    end
  end

  resources :conversations, only: [:create] do
    member do
      post :close
    end

    resources :messages, only: [:create]
  end



  # resources :orders do
  #   member do
  #     post :transactions
  #   end
  # end

  scope path: '/api/v1/', module: 'api_v1', as: 'v1'  do
    get '/search/keyword' => 'search#keyword'
    get '/search/filter' => 'search#filter'
    get '/cuisines/get_foods' => 'cuisines#get_foods'
    get '/cuisines/get_restaurants' => 'cuisines#get_restaurants'
  end
  scope path: '/api/v1/', module: 'api_v1', as: 'v1', defaults: { format: :json } do
    get '/getDishesByFilter' => 'mains#getDishesByFilter'
    get '/getRestaurantsByMap' => 'restaurants#getRestaurantsByMap'
    get '/check_delivery_location' => 'orders#check_delivery_location'
  end


end

app/controllers/admin/restaurants_controller.rb
class Admin::RestaurantsController < ApplicationController

	layout "admin"

	before_action :user_admin?
	before_action :find_restaurant, :only =>[:show, :update, :destroy]

	def index
		@restaurants = Restaurant.page(params[:page]).per(5)
	end

	def show
		@foods = @restaurant.foods.all
	end

	def update

		if params[:is_approved]
			if params[:is_approved] == "1"
				@restaurant.is_approved = true
				@restaurant.save!

			elsif params[:is_approved] == "0"
				@restaurant.is_approved = false
				@restaurant.save!
			end
		end

		redirect_to :back
	end

	def destroy
		@restaurant.is_live = false
		@restaurant.save!

		if params[:rescue] == "1"
			@restaurant.is_live = true
			@restaurant.save!
		end

		redirect_to :back
	end

	private

	def find_restaurant
		@restaurant = Restaurant.find(params[:id])
	end

end

app/controllers/api_v1/restaurants_controller.rb
class ApiV1::RestaurantsController < ApiController

	def getRestaurantsByMap
		coordinate
		@restaurants = Restaurant.where( latitude: coordinate[:south]..coordinate[:north],
																																			longitude: coordinate[:west]..coordinate[:east] ).limit(params[:qty]).sample(9)
		@hash = Gmaps4rails.build_markers(@restaurants) do |restaurant, marker|
			marker.lat restaurant.latitude
			marker.lng restaurant.longitude
			marker.infowindow restaurant.address
			marker.json({ id: restaurant.id,
																	close_url: "#{ ActionController::Base.helpers.image_path 'close.png'}",
																	html: gmap_html(restaurant,0.5) })
		end
		render json: { gmap_hash: @hash, qty: @hash.size }, status: 200
	end

	private

	def coordinate
		coordinate = {}
		coordinate[:north] = params[:north].to_f
		coordinate[:east] = params[:east].to_f
		coordinate[:south] = params[:south].to_f
		coordinate[:west] = params[:west].to_f
		coordinate
	end

	def gmap_html(restaurant,rating)
		group = []
		imgs = %w{http://i.stack.imgur.com/R5yzx.jpg http://i.stack.imgur.com/k0Hsd.jpg http://i.stack.imgur.com/Hhl9H.jpg http://i.stack.imgur.com/r1AyN.jpg http://i.stack.imgur.com/EHHsa.jpg}
		imgs.each_with_index do |img,i|
			group << "<div class='group'>
          						<input type='radio' name='test' id='#{i}' value='#{i}' #{'checked' if i ==0 }>
          						<label for='#{i-1 < 0 ? imgs.size - 1 : i-1}' class='previous'></label>
          						<label for='#{i+1 > imgs.size - 1 ? 0 : i+1}' class='next'></label>
          						<div class='content'>
          							<img style='background-image:url(#{img})'>
          						</div>
          					</div>"
		end

		html = "<div class='gmap_cards'>
		<div class='ui fluid card'>
          	<div class='image'>
          		<div class='css_carousel'>
          			<div class='wrap'>
          				<div class='wrap2'>
          				#{group.join('')}
          				</div>
          			</div>
          		</div>
          	</div>
          	<div class='content'>
              <h4><p class='description'><a href='/'>#{ restaurant.name }</a></p></h4>
									<hr>
							  <div class='flex_center_start location'>
											<div class='flex_center'>
												<p>#{restaurant.address}</p>
											</div>
                  </div>
								<hr>
                  <div class='rating_wrapping'>
                    <div class='show_rated_#{ rating.to_s.gsub!('.','_') }'></div>
                    <span name='reivews'>200 Reviews</span>
                  </div>
                  <div class='num_counts'>
                    #{ActionController::Base.helpers.image_tag 'heart_icon.png'}
                    <span>102 Likes</span>
                    #{ActionController::Base.helpers.image_tag 'plate_icon.png'}
                    <span>238 Orders</span>
                  </div>
                  <div class='meta hidden-xs'>
                    <span><a href'>Vegan</a></span><span><a href'>Soup</a></span><span><a href'>Pumkim</a></span><span><a href'>Autum</a></span>
                  </div>

                </div>
          </div>
			</div>"
		return html
	end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  before_action :find_restaurant, :except => [:index]
  before_action :find_chef, :except => [:index]
  before_action :get_today_foods_ids, :except => [:index]

  def index
    @user = User.new
  end

  def show
    @user = current_user || User.new

    time_range = (Time.now.localtime.beginning_of_day().utc..Time.now.localtime.end_of_day().utc)
    @today_orders = @chef.restaurant.orders.where(:payment_status => "paid").where(:pick_up_time => time_range)

    if @restaurant.order_reach > 0
      @reach_percent = (@today_orders.sum(:amount)*100/@restaurant.order_reach).to_f
    else
      @reach_percent = 0
    end

    # show today & advance foods
    wday_now = Time.now.localtime.wday

    @today_foods_ids = get_today_foods_ids
    @today_foods = Food.where(id:@today_foods_ids)


    # advance 的 example
    @date = deal_params_date(params[:date])
    @advance_foods_ids = get_in_advance_foods_ids(@date)
    @advance_foods = Food.where(id: @advance_foods_ids)

    # score_rate_i = @restaurant.food_avg_summary_score.to_i
    # score_rate_f = ((@restaurant.food_avg_summary_score - score_rate_i)/0.5).to_i
    # @score_rate = score_rate_i.to_s + ("_5" * score_rate_f)

    array = []
    bigbun = @restaurant.get_available_bigbun
    if bigbun
      # 剩下的可用的bigbun 數量
      left_num = bigbun.availible_num
      array << [@restaurant, bigbun, left_num]
    end
    @restaurant_available_bigbun_array = array


    respond_to do |format|
      format.html
      format.js
    end
  end

  def get_conversation_with_chef
    if current_user && current_user != @chef.user
      @recipient = @chef.user
      @sender = current_user

      @conversation = Conversation.find_by(
                        :recipient_id => @recipient.id,
                        :sender_id => @sender.id)
      @messages = @conversation.messages

    else
      # 非登入者
    end

    respond_to do |format|
        format.js
    end

  end

  private

  def deal_params_date(params)
    params.to_time.strftime('%F')
  rescue
    Date.current.to_time.strftime('%F')
  end

  def find_restaurant
    @restaurant = Restaurant.includes(:big_buns,:bulk_buys).find(params[:id])
  end

  def find_chef
    @chef = @restaurant.chef
  end

  def get_today_foods_ids
    wday_now = Time.now.localtime.wday
    today_foods_ids = []
    public_foods = @restaurant.foods.where(:is_public => true)

    public_foods.each do |food|
      today_foods_ids << food.id if food.support_days.include?(wday_now)
    end

    today_foods_ids
  end

  def get_in_advance_foods_ids(date)
    wday = date.to_time.localtime.wday
    advance_foods_ids = []
    public_foods = @restaurant.foods.where(:is_public => true)

    public_foods.each do |food|
      advance_foods_ids << food.id if food.support_days.include?(wday)
    end

    advance_foods_ids
  end

end

app/helpers/admin/restaurants_helper.rb
module Admin::RestaurantsHelper
end

app/helpers/api_v1/restaurants_helper.rb
module ApiV1::RestaurantsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper

	# FAKE
	def certificated_by
	end

	def certificated_date
	end
end

app/views/admin/restaurants/index.html.erb
<div id="page-content-wrapper">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-12">
        <div id="custom-search-input">
          <div class="input-group col-md-12">
            <input type="text" class="form-control input-lg" placeholder="Search" />
            <span class="input-group-btn">
              <button class="btn btn-info btn-lg" type="button">
                <i class="fa fa-search"></i>
              </button>
            </span>
          </div>
        </div>
        <%= form_tag admin_restaurants_path do %>
          <%= text_field_tag "keyword", :class => "form-control input-lg"%>
          <%= submit_tag "Search",:class => "btn btn-info btn-lg" %>
        <% end %>
      </div>
      <div class="col-md-12">
        <h1>Restaurants List</h1>
        <table class="table table-striped table-hover">
          <thead>
            <tr>
              <th>Restaurant ID</th>
              <th>Restaurant Name</th>
              <th>Created_on</th>
              <th>Approved</th>
              <th>Boss ID</th>
              <th>Boss Name</th>
              <th>Boss Email</th>
              <th>Orders Count</th>
              <th>Orders View</th>
              <th>Total Acount</th>
              <th>Delete</th>
            </tr>
          </thead>
          <tbody>
            <% @restaurants.each do |r|%>
              <tr data-toggle="collapse" data-target="#data<%=r.id%>" class="accordion-toggle">
                  <td>
                    <%= link_to r.id, admin_restaurant_path(r)%>
                  </td>
                  <td>
                    <%= link_to r.name, admin_restaurant_path(r)%>
                  </td>
                  <td><%=r.created_at%></td>
                  <td style="text-align:center;">
                    <% if r.is_approved%>
                      <div style="color:white; background-color: green; border-radius: 5px; "><%= r.is_approved %></div>
                    <% else %>
                      <div ><%= r.is_approved %></div>
                    <% end %>
                  </td>
                  <td><%=r.chef.id%></td>
                  <td><%=r.chef.first_name %> <%= r.chef.last_name %></td>
                  <td><%=r.chef.user.email%></td>
                  <td>6</td>
                  <td>
                    <div class="btn btn-success">
                      check
                    </div>
                  </td>
                  <td>$<%= r.orders.sum(:amount)%></td>
                  <td style="text-align:center;">
                    <% if r.is_live%>
                      <div></div>
                    <% else %>
                      <div style="color:white; background-color: red; border-radius: 5px; ">Delete</div>
                    <% end %>
                  </td>
              </tr>
              <tr >
                <td colspan="13" class="hiddenRow">
                  <div class="accordian-body collapse" id="data<%=r.id%>">
                    <div class="container-fluid">
                      <div class="row">
                        <table class="table table-bordered">
                          <thead>
                            <tr>
                              <th>Order ID</th>
                              <th>Scheduled Datetime</th>
                              <th>Customer ID</th>
                              <th>Customer Name</th>
                              <th>Customer Email</th>
                              <th>Content</th>
                              <th>Shipping method</th>
                              <th>Shipping place</th>
                              <th>Total Amount</th>
                              <th>payment method</th>
                              <th>payment status</th>
                              <th>shipping status</th>
                              <th>order status</th>
                            </tr>
                          </thead>
                          <tbody>
                            <% r.orders.each do |order|%>
                              <tr data-toggle="collapse" data-target="#data1" class="accordion-toggle">
                                <td><%=order.id%></td>
                                <td><%=order.pick_up_time%></td>
                                <td><%=order.user.id%></td>
                                <td><%=order.customer_name%></td>
                                <td><%=order.user.email%></td>
                                <td>
                                  <% order.foods.each do |food|%>
                                      <%= food.name%>
                                      *
                                      <%= order.order_food_ships.find_by(:food_id => food.id).quantity%>
                                      ($<%=order.order_food_ships.find_by(:food_id => food.id).amount%>)
                                  <% end %>

                                </td>
                                <td><%=order.shipping_method%></td>
                                <td><%=order.shipping_place%></td>
                                <td><%=order.amount%></td>
                                <td><%=order.payment_method%></td>
                                <td><%=order.payment_status%></td>
                                <td><%=order.shipping_status%></td>
                                <td><%=order.order_status%></td>
                              </tr>
                            <% end %>
                          </tbody>
                        </table>
                      </div>
                    </div>
                  </div>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>

  <div class="center" style="text-align: center; font-size: 20px;">
    <%= paginate @restaurants %>
  </div>
</div>

app/views/admin/restaurants/show.html.erb
<div class="admin-show-table">
	<div class="row">
		<h1>Restaurant show</h1>
	</div>

	<h3>ID:
		<%= @restaurant.id %>
	</h3>

	<h3>Name:
		<%= @restaurant.name %>
	</h3>

	<h3>Boss:
		<%= @restaurant.chef.first_name %> <%= @restaurant.chef.last_name %>
	</h3>

	<h3>Address:
		<%= @restaurant.address %>
	</h3>

	<h3>phone_number:
		<%= @restaurant.phone_number %>
	</h3>

	<h3>description:
		<%= @restaurant.description %>
	</h3>

	<h3>Foods:</h3>
	<table class="table table-striped">
		<thead>
			<th>Food Name</th>
			<th>Price</th>
		</thead>
		<tbody>
			<% @foods.each do |f| %>
				<tr>
					<td><%= f.name %></td>
					<td><%= f.price %></td>
				</tr>

			<% end %>
		</tbody>
	</table>

	<h3>created_at:
		<%= @restaurant.created_at %>
	</h3>

	<h3>updated_at:
		<%= @restaurant.updated_at %>
	</h3>

	<h3>is_live:
		<%= @restaurant.is_live %>
		<% if @restaurant.is_live%>
      <%= link_to('Delete', admin_restaurant_path(@restaurant),:class => "btn-sm btn-danger", :method => "DELETE")%>
    <% else %>
      <%= link_to('Rescue', admin_restaurant_path(@restaurant,:rescue => 1),:class => "btn-sm btn-default", :method => "DELETE")%>
    <% end %>
	</h3>

	<h3>is_approved:
		<%= @restaurant.is_approved %>

		<% if @restaurant.is_approved%>
	    <%= link_to('Ban', admin_restaurant_path(@restaurant,:is_approved => 0),:class => "btn-sm btn-danger", :method => "PATCH")%>
	  <% else %>
	    <%= link_to('Approved', admin_restaurant_path(@restaurant,:is_approved => 1),:class => "btn-sm btn-success", :method => "PATCH")%>
	  <% end %>
	</h3>

</div>