config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/home_admin', as: 'rails_admin'
  get 'transactions/new'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  root :to => "main#index"

  get "main/index" => "main#index"
  get "admin" => "admin/users#index"


  get 'conditions' => 'main#conditions'
  get 'terms' => 'main#terms'

  namespace :admin do
    resources :main
    resources :orders do
      collection do
        get :today
      end
    end
    resources :users
    resources :restaurants
  end

  resources :users do
    member do
      get :purchase

      # ajax btn
      get :paid
      get :completed
      get :cancelled
      get :big_bun

      # update order btn
      post :cancel_order
      post :not_yet_order
      post :yep_order

      get :review
      get :message

      get :liked
      get :kitchen
      get :food

      post :like
      post :unlike

      # conversation
      get :get_conversation_messages

    end
  end

  resources :chefs do
    resources :foods
    resources :big_buns
    resources :replies
    member do
      get :review
      get :approve

      # Menu
      get :add_dish
      post :save_dish
      get :add_big_bun
      get :menu

      # 5 btn
      get :sales
      get :summary
      get :advance
      get :delivering
      get :completed
      get :cancelled

      get :income
      get :rating
      get :message
      get :business

      #yep
      post :yep_or_not

      #report
      get :orders_to_csv

      # conversation
      get :get_conversation_messages

    end
  end

  resources :foods

  resources :restaurants do
    resources :orders, controller: :orders do
      member do
        post :transactions
      end
    end

    resources :comments do
      member do
        post :update_food_comment
      end

      collection do
        post :create_food_comment
      end
    end

    member do
      get :get_conversation_with_chef
    end
  end

  resources :big_buns do
    collection do
      post :user_get_big_bun
      post :user_send_big_bun_as_gift
    end
  end

  resources :conversations, only: [:create] do
    member do
      post :close
    end

    resources :messages, only: [:create]
  end



  # resources :orders do
  #   member do
  #     post :transactions
  #   end
  # end

  scope path: '/api/v1/', module: 'api_v1', as: 'v1'  do
    get '/search/keyword' => 'search#keyword'
    get '/search/filter' => 'search#filter'
    get '/cuisines/get_foods' => 'cuisines#get_foods'
    get '/cuisines/get_restaurants' => 'cuisines#get_restaurants'
  end
  scope path: '/api/v1/', module: 'api_v1', as: 'v1', defaults: { format: :json } do
    get '/getDishesByFilter' => 'mains#getDishesByFilter'
    get '/getRestaurantsByMap' => 'restaurants#getRestaurantsByMap'
    get '/check_delivery_location' => 'orders#check_delivery_location'
  end


end

app/views/common/_add_to_cart.html.erb
<div class="add_to_cart" data-link="<%= new_restaurant_order_path(@restaurant ? @restaurant : @food, date: Date.current) %>"
     data-original-link="<%= new_restaurant_order_path(@restaurant ? @restaurant : @food) %>">

  <h3 class="dib"><i class="cart_icon_white"></i>$<span name="cart_total_price">0</span></h3>
  <a href="<%= new_restaurant_order_path(@restaurant ? @restaurant : @food, date: Date.current) %>"><button>NEXT</button></a>
</div>


<style>
  .footer,.back_to_top{
    display: none !important;
  }
  body{
    padding-bottom: 80px;
  }
</style>

app/views/common/_advance_product_list.html.erb
<div class="row df_sm mb20_md">
  <div class="col-sm-6 col-xs-12 list_status_carousel">
    <% if food.food_photos.present? %>
        <%= render 'common/product_carousel' ,food:food %>
    <% end %>
  </div>
  <div class="col-sm-6 col-xs-12 pl100_md pl60_sm list_status_info">
    <div>
      <h3 class="mt15 mt5_sm"><%= food.name %></h3>
    </div>
    <div>
      <h3 class="red">$<%= food.price %>/ Bowl</h3>
    </div>
    <div class="food_data_info advance_food" data-advance-time="<%= @date %>" <%= food_restaurant_info(food) %>>
      <%= render 'common/spinner', qty: 0  %>
    </div>
    <div>
      <h4 class="blck normal">2 Left <i class="l_line"></i> 12 Ordered</h4>
    </div>
    <div>
      <h4 class="black mt25 mb25">Ingredients: <p class="mt10" style="font-size: 18px;"><%= truncate(food.ingredients,length: 70) %></p>
      </h4>
    </div>
    <div class="hidden-sm mb20 mb0_sm">
      <i class="fa fa-heart red mr25 mt20_sm" aria-hidden="true" name="heart"></i><i class="share_icon_red" name="shard"></i>
      <a href="" class="gray flr mt0_sm mt15_md"><h4>More...</h4></a>
    </div>
  </div>
</div>
<div class="row list_status_social_link mtb15_sm">
  <div class="col-xs-6 visible-sm tar">
    <i class="fa fa-heart red mr25" aria-hidden="true" name="heart"></i><i class="share_icon_red" name="shard"></i>
  </div>
  <div class="col-xs-6 visible-sm">
    <a href="" class="gray flr"><h4>More...</h4></a>
  </div>
</div>

app/views/common/_auth_link.html.erb
<div class="ui small modal background_red" id="auth_link_modal">
  <button class="ui button my_btn bold login">
    Log in
  </button>
  <h2 class="tac bold">or</h2>
  <button class="ui button my_btn bold sign_up">
    Join us & Check out
  </button>
</div>

app/views/common/_back_to_top.html.erb
<a href="#top">
  <div class="back_to_top hidden-xs" data-tooltip="Back to top" data-inverted=""  id="back_to_top">
    <%= image_tag 'icon/back_top.png' %>
  </div>
</a>

<script type="text/javascript" charset="utf-8">
  var back_btn = $('#back_to_top');
  var back_top_minus_hight = 920
  back_btn.data('top',parseInt(back_btn.css('top')))
  var hide_back_button;
  (hide_back_button = function() {
    $(window).scrollTop() < $(window).height()/2 ? back_btn.hide() : back_btn.show()
  })();
  $(document).ready(function(){
    $(window).scroll(function () {
      hide_back_button()
      var scroll = $(window).scrollTop();
      var top = back_btn.data('top')
      var height = $('body')[0].scrollHeight - back_top_minus_hight
      if(height < scroll ){
        var a = scroll-height;
        back_btn.css('top',top - a)
      }else{
        back_btn.css('top',top)
      }
    });
  })
</script>

app/views/common/_bigbun.html.erb
<div class="ui modal bigbun_modal" id="bigbun_modal_<%= food.try(:id) %>" data-bigbun-id="<%= bigbun.id %>" data-prepare-time="<%= bigbun.prepare_time.in_time_zone %>" data-stop-time="<%= bigbun.stop_datetime.in_time_zone %>" data-restaurant-id="<%= restaurant.id %>">
  <i class="close icon"></i>
  <h4 class="bold">Congratulation!</h4>
  <i class="gray_line"></i>
  <div class="description">
    <h4>You got a free bowl of egg drop soup!</h4>
    <h4 class="bold red">Code: <span id="bigbun_code"><%= bigbun.code %></span></h4>
    <div class="image">
      <%= image_tag 'tmp/soup.png' %>
    </div>
  </div>
  <div class="action_bottons">
    <button class="ui button my_btn" id="redeem_now">Redeem now</button>
    <button class="ui button my_btn_reserve" id="use_later">Use later</button>
    <button class="ui button my_btn" id="send_gift">Send as gift</button>
  </div>


  <div class="ui modal gift_email_modal" data-bigbun-id="<%= bigbun.id %>">
    <i class="close icon"></i>
    <h4 class="bold">Enter your Email</h4>
    <i class="gray_line"></i>
    <div class="description">
      <div class="ui form">
        <div class="field">
          <input type="email">
        </div>
      </div>
    </div>
    <div class="action_bottons">
      <button class="ui button my_btn" id="send_gift_confirmation">Confirmation</button>
    </div>
  </div>


</div>

app/views/common/_footer.html.erb
<div class="footer col-xs-12">
  <div class="row">
    <div class="footer-first">
      <div class="col-md-3">
        <p>CONTACT</p>
        <p><i class="fa fa-envelope" aria-hidden="true"></i>hello@gmail.com</p>
        <p><i class="fa fa-phone" aria-hidden="true"></i>601-123-456</p>
      </div>
      <div class="col-md-3">
        <%= link_to 'ABOUT' ,{} %>
        <%= link_to 'BECOME A CHEF' ,{} %>
        <%= link_to 'LOG IN' ,{} %>
        <%= link_to 'SIGN UP' ,{} %>
      </div>
      <div class="col-md-3">
        <div class="col-md-12">
          <p><i class="fa fa-globe" aria-hidden="true"></i>中文</p>
        </div>
        <div class="col-md-12">
          <p>Follow us on</p>
        </div>
        <div class="col-md-12">
          <i class="fa fa-facebook square_icon" aria-hidden="true"></i>
          <i class="fa fa-twitter square_icon" aria-hidden="true"></i>
          <i class="fa fa-google-plus square_icon" aria-hidden="true"></i>
        </div>
      </div>
    </div>
    <div class="footer-last">
      <span>&copy; Homeaste2016</span><span><a href="<%= terms_path %>">Terms</a></span> <span><a href="<%= conditions_path %>">Privacy</a></span>
    </div>
  </div>
</div>

app/views/common/_login_form.html.erb
<div class="ui small modal" id="login_modal">
  <i class="close icon"></i>
  <div class="content">
    <div class="ui form my_form">
      <%= form_for(@user, url: session_path(@user)) do |f| %>
          <div class="field">
            <%= f.email_field :email, autofocus: true, placeholder: "Email" ,style:'color:#fff !important;' %>
          </div>

          <div class="field">
            <%= f.password_field :password, autocomplete: "off" , placeholder: "Password",style:'color:#fff !important;' %>
          </div>
          <%= link_to "Forgot your password?", new_password_path(@user) ,name:'forgot_password' %>
          <div class="actions">
            <%= f.submit "Log in" , :id => "login_btn"%>
          </div>
      <% end %>

    </div>

  </div>
  <div class="col-xs-12">
    <div class="row outh_logo">
      <p>Log in with</p>
      <%= link_to user_facebook_omniauth_authorize_path do %>
          <i class="fa fa-facebook square_icon" aria-hidden="true"></i>
      <% end %>
      <%= link_to user_google_oauth2_omniauth_authorize_path do %>
          <i class="fa fa-google-plus square_icon" aria-hidden="true"></i>
      <% end %>
      <i class="fa fa-weixin square_icon" aria-hidden="true"></i>
    </div>
  </div>
</div>

app/views/common/_message_room.html.erb
<div class="message_content" id="conversations-list">
  <div class="message_top white col-xs-12">
    <div class="row">
      <div class="col-xs-1">
        <i class="fa fa-angle-left visible-xs visible-sm cursor_pointer"></i>
      </div>
      <div class="col-xs-10" style="height: 70px;">
        <div class="background_img_setting border_main_radius" style="background-image: url(<%= image_path 'tmp/product.png' %>);"></div>
        <h4 class="mtb10" style="font-size: 18px;"><%= @recipient.name %></h4>

        <% if @messages.size > 0%>
            <span><%=@messages.last.updated_at.localtime.strftime("%Y-%m-%d %H:%M:%S")%></span>
        <% end %>
      </div>
    </div>
  </div>
  <div class="message_body col-xs-12" data-conversation-id="<%= @conversation.id %>">
    <div class="mb15">
      <div class="background_img_setting border_main_radius mtn_sm fll" style="background-image: url(<%= image_path 'tmp/product.png' %>);"></div> <!-- TODO:這是什麼？請幫我補前端 -->
      <h4 style="line-height: 70px;" class="ml10"><%= @recipient.name %></h4>
    </div>
    <div class="row messages-list">
      <div class="col-xs-12 messages">
        <ul>
          <% @messages.each do |message|%>
              <li>
                  <%if message.user_id == @sender.id%>
                      <% message_type = "message-sent message-right" %>
                  <%else%>
                      <% message_type = "message-received message-left" %>
                  <%end%>
                  <div class="<%=message_type%>">
                    <%=message.body%>
                  </div>
              </li>
          <%end%>
        </ul>
      </div>
    </div>
  </div>
  <div class="message_bottom col-xs-12">
    <form class="new_message">
      <input name="conversation_id" type="hidden" value="<%= @conversation.id %>">
      <input name="user_id" type="hidden" value="<%= @sender.id %>">
      <textarea name="body" class="form-control"></textarea>
      <input type="submit" class="submit" value="Send">
    </form>
  </div>
</div>

app/views/common/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">
        <%= image_tag 'logo.png' %>
        HOMETASTE
      </a>
    </div>

    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <% unless @chef %>
            <li><a href="#">Help</a><span class="hidden-xs">|</span></li>
            <li><%= link_to 'Become a chef', new_chef_path %><span class="hidden-xs">|</span></li>
        <% end %>

        <% if current_user %>
            <div class="ui selection dropdown hidden-xs">
              <i class="dropdown icon"></i>
              <div class="default text">Hi! <%= current_user.name %></div>
              <div class="menu">

                <% if current_user.is_chef %>
                    <div class="item"><%= link_to('Chef’s Homepage', sales_chef_path(current_user.chef)) %></div>
                    <div class="item"><%= link_to('Menu', menu_chef_path(current_user.chef)) %></div>
                    <div class="item"><%= link_to('Sign out', destroy_user_session_path, :method => :delete) %></div>
                <% else %>

                    <div class="item"><%= link_to('My account', purchase_user_path(current_user)) %></div>
                    <div class="item"><%= link_to('Message',message_user_path(current_user)) %></div>
                    <div class="item"><%= link_to('Sign out', destroy_user_session_path, :method => :delete) %></div>
                <% end %>
              </div>
            </div>
        <% end %>

        <% if current_user %>

            <% if current_user.is_chef %>
                <li class="visible-xs"><%= link_to('Chef’s Homepage', sales_chef_path(current_user.chef)) %></li>
                <li class="visible-xs"><%= link_to('Menu', menu_chef_path(current_user.chef)) %></li>
                <li class="visible-xs"><%= link_to('Sign out', destroy_user_session_path, :method => :delete) %></li>

            <% else %>
                <li class="visible-xs"><%= link_to('My account', purchase_user_path(current_user)) %></li>
                <li class="visible-xs"><%= link_to('Message',message_user_path(current_user)) %></li>
                <li class="visible-xs"><%= link_to('Sign out', destroy_user_session_path, :method => :delete) %></li>
            <% end %>

        <% else %>
            <li><a class="sign_up">Sign up</a><span class="hidden-xs">|</span></li>
            <li><a class="login">Log In</a></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>
<%= render 'common/login_form' %>
<%= render 'common/sign_up_form' %>
<%= render 'common/auth_link' %>

app/views/common/_product_carousel.html.erb
<div id="productCarousel_<%= food.id %>" class="carousel slide product_carousel" data-ride="carousel">
  <ol class="carousel-indicators">
    <% food.food_photos.each_with_index do |photo,index| %>
        <li data-target="#productCarousel_<%= index %>" data-slide-to="<%= index %>" class="<%= 'active' if index == 0 %>"></li>
    <% end %>
  </ol>

  <div class="carousel-inner" role="listbox">
    <% food.food_photos.each_with_index do |photo,index| %>
        <div class="item <%= 'active' if index == 0 %>">
          <div style="background-image: url(<%= image_path photo.photo.url %>);" class="background_img_setting" data-food-id-pic="<%= food.id %>"></div>
        </div>
    <% end %>
  </div>

  <a class="left carousel-control" href="#productCarousel_<%= food.id %>" role="button" data-slide="prev">
    <i class="fa fa-angle-left fa-2x" aria-hidden="true"></i>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#productCarousel_<%= food.id %>" role="button" data-slide="next">
    <i class="fa fa-angle-right fa-2x" aria-hidden="true"></i>
    <span class="sr-only">Next</span>
  </a>
</div>

app/views/common/_product_list.html.erb
<div class="row df_sm mb20_md">
  <div class="col-sm-6 col-xs-12 list_status_carousel">
    <% if food.food_photos.present? %>
        <%= render 'common/product_carousel' ,food:food %>
    <% end %>
  </div>
  <div class="col-sm-6 col-xs-12 pl100_md pl60_sm list_status_info">
    <div>
      <h3 class="mt15 mt5_sm"><%= food.name %></h3>
    </div>
    <div>
      <h3 class="red">$<%= food.price %>/ Bowl</h3>
    </div>
    <div class="food_data_info <%= advance %>" <%= food_restaurant_info(food) %>>
      <%= render 'common/spinner', qty: 0  %>
    </div>
    <div>
      <h4 class="blck normal">2 Left <i class="l_line"></i> 12 Ordered</h4>
    </div>
    <div>
      <h4 class="black mt25 mb25">Ingredients: <p class="mt10" style="font-size: 17px;"><%= truncate(food.ingredients,length: 70) %></p>
      </h4>
    </div>
    <div class="hidden-sm mb20 mb0_sm">
      <%= link_to like_user_path(food_id: food.id, user_id: current_user.try(:id)), method:'post', remote:true,
                  class:"food_liking_#{food.id} #{'hidden' if current_user && current_user.user_food_likings.pluck(:food_id).include?(food.id)}" do %>
          <i class="fa fa-heart-o red mr25 mt20_sm" aria-hidden="true" name="heart"></i><i class="share_icon_red" name="shard"></i>
      <% end %>

      <%= link_to unlike_user_path(food_id: food.id, user_id: current_user.try(:id)), method:'post',remote:true,
                  class:"food_unliking_#{food.id} #{'hidden' unless current_user && current_user.user_food_likings.pluck(:food_id).include?(food.id)}" do %>
          <i class="fa fa-heart red mr25 mt20_sm" aria-hidden="true" name="heart"></i><i class="share_icon_red" name="shard"></i>
      <% end %>

      <a href="" class="gray flr mt0_sm mt15_md"><h4>More...</h4></a>
    </div>
  </div>
</div>
<div class="row list_status_social_link mtb15_sm">
  <div class="col-xs-6 visible-sm tar">
    <i class="fa fa-heart red mr25" aria-hidden="true" name="heart"></i><i class="share_icon_red" name="shard"></i>
  </div>
  <div class="col-xs-6 visible-sm">
    <a href="" class="gray flr"><h4>More...</h4></a>
  </div>
</div>

app/views/common/_sign_up_form.html.erb
<div class="ui small modal" id="sign_up_modal">
  <i class="close icon"></i>
  <div class="content">
    <div class="ui form my_form">
      <%= form_for(@user, url: registration_path(@user)) do |f| %>

          <div class="field">
            <%#= f.text_field :foodie_id, :placeholder => "Foodie ID"%>
          </div>

          <div class="field">
            <%= f.text_field :name, :placeholder => "Your Name"%>
          </div>

          <div class="field">
            <%= f.email_field :email, autofocus: true , :placeholder => "Email"%>
          </div>

          <div class="field">
            <%= f.text_field :phone_number, :placeholder => "Phone Number"%>
          </div>

          <div class="field">
            <% if @minimum_password_length %>
                <em>(<%= @minimum_password_length %> characters minimum)</em>
            <% end %>
            <%= f.password_field :password, autocomplete: "off", :placeholder => "Password"%>
          </div>

          <div class="field">
            <%= f.password_field :password_confirmation, autocomplete: "off", :placeholder => "Confirm Password" %>
          </div>
          <span name="term">By singing up,you agree with our <a href="<%= terms_path %>">terms</a> and <a href="<%= conditions_path %>">conditions.</a></span>
          <div class="actions">
            <%= f.submit "Sign up" ,class:'ui button my_btn', :id =>"sign_up_btn"%>
          </div>
      <% end %>
    </div>

  </div>
  <div class="row outh_logo">
  <div class="col-xs-12">

      <p >Sign up with</p>
      <%= link_to user_facebook_omniauth_authorize_path do %>
          <i class="fa fa-facebook square_icon" aria-hidden="true"></i>
      <% end %>
    <%= link_to user_google_oauth2_omniauth_authorize_path do %>
        <i class="fa fa-google-plus square_icon" aria-hidden="true"></i>
    <% end %>
      <i class="fa fa-weixin square_icon" aria-hidden="true"></i>
    </div>
  </div>
</div>

app/views/common/_spinner.html.erb
<div class="ui form product_item">
  <div class="count_spinner">
    <div class="ui mini buttons">
      <%= button_tag type:"button", class:"ui icon button product_spineer_button", command:"Down" do  %>
          <i class="minus_icon_black"></i>
      <% end %>
      <%= text_field_tag :qty ,0, id:"txtNum", min:"0", readonly: true %>
      <%= button_tag type:"button", class:"ui icon button product_spineer_button", command:"Up" do  %>
          <i class="add_icon_black"></i>
      <% end %>
    </div>
  </div>
</div>